defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_time: 10.0

data:
  n_coils: 1
  smaps: false
  dtype: "complex64"

trajectory: "trajs/trajectory_floret.bin"
task:
  - forward
  - adjoint
  - grad
backend: "finufft"

monitor:
  interval: 0.5
  gpu: true

hydra:
  job:
    chdir: true
